Adding solution for level 1
NataliiaRemezova/typing_challenges pull request #1
Opened 2024-02-23 15:57 UTC by NataliiaRemezova

2024-02-24 14:41 UTC, vppuzakov requested changes
👍 в целом неплохо, в некоторых заданиях нужно задать тип поточнее. Можешь подпушить прямо в эту ветку и прислать этот же ПР еще раз на проверку.

2024-02-24 14:41 UTC, vppuzakov commented on level_1/1.py
> +def is_user_banned(user_id: int) -> bool:
👍 верно

2024-02-24 14:41 UTC, vppuzakov commented on level_1/10.py
> +def stringify(value: any) -> str:
❗ да, есть такая возможность задать любой тип - она задается вот таким образом

```python
from typing import Any
```

💡 хотя в данном случае будет более верным использовать перечисление ([Union](https://docs.python.org/3/library/stdtypes.html#union-type)) возможных типов на входе - чем точнее мы зададим аннотации - тем лучше нам будет помогать mypy.

2024-02-24 14:41 UTC, vppuzakov commented on level_1/2.py
> +def is_adult(age: int, country_name: str) -> bool:
👍 верно

2024-02-24 14:41 UTC, vppuzakov commented on level_1/3.py
> +def compose_full_name(first_name: str, last_name: str, middle_name: str) -> str:
💡 почти верно, обрати внимание, что отчество может отсутствовать, для указания этого можно использовать [Optional](https://docs.python.org/3/library/typing.html#typing.Optional), еще лучше его более короткую форму: 

> Changed in version 3.10: Optional can now be written as X | None.

2024-02-24 14:41 UTC, vppuzakov commented on level_1/4.py
> +def calculate_age(date_of_birth: datetime.date) -> int:
👍 верно

2024-02-24 14:41 UTC, vppuzakov commented on level_1/5.py
> +def is_correct_email(raw_email: str) -> bool:
👍 верно

2024-02-24 14:41 UTC, vppuzakov commented on level_1/6.py
> +def is_loan_amount_too_big(loan_amount_usd: int, max_loan_amount_for_user_usd: int) -> bool:
💡 обрати внимание на `опциональность` одного из параметров - в аннотациях явно нужно отразить этот момент.

2024-02-24 14:41 UTC, vppuzakov commented on level_1/7.py
> +def send_email(header: str, text_content: str, send_to: str) -> None:
👍 верно, то, что функция ничего не возвращает стоит указывать явно

2024-02-24 14:41 UTC, vppuzakov commented on level_1/8.py
> +def get_user_balance(user_id: uuid.UUID) -> decimal.Decimal:
👍 верно

2024-02-24 14:41 UTC, vppuzakov commented on level_1/9.py
> +def is_correct_int(raw_int: int) -> bool:
❗ на входе на самом деле не число, посмотри внимательно, а также обрати внимание на `None`

2024-02-24 14:41 UTC, vppuzakov requested changes
👍 в целом неплохо, в некоторых заданиях нужно задать тип поточнее. Можешь подпушить прямо в эту ветку и прислать этот же ПР еще раз на проверку.

2024-03-01 22:37 UTC, NataliiaRemezova commented
@vppuzakov, большое спасибо за комментарии! Исправила ошибки, добавила новый коммит.

2024-03-07 00:05 UTC, vppuzakov approved these changes
👍 все супер! вмерживай

2024-03-07 00:05 UTC, vppuzakov commented on level_1/10.py
> +def stringify(value: str | int | float | None) -> str:
👍 отлично

2024-03-07 00:05 UTC, vppuzakov commented on level_1/3.py
> +def compose_full_name(first_name: str, last_name: str, middle_name: str | None) -> str:
👍 верно

2024-03-07 00:05 UTC, vppuzakov commented on level_1/6.py
> +def is_loan_amount_too_big(loan_amount_usd: int, max_loan_amount_for_user_usd: int | None) -> bool:
👍 отлично

2024-03-07 00:05 UTC, vppuzakov commented on level_1/9.py
> +def is_correct_int(raw_int: str | None) -> bool:
👍 верно

2024-03-08 17:48 UTC, merged